### ISSUE TITLE
stored api key is not used: recognition does not work

### ISSUE THREAD

**Issue by wuppiwuppi** [j4ym0/nextcloud-tv-show-namer#14]
Hi, 

thanks for the effort and the updates in the last 2 weeks. 
The api key is now stored and I received a pop up saying so. 

In the latest version 0.4.0 it looks like that:
![image](https://user-images.githubusercontent.com/62333594/203727923-01c95f73-9a46-4df0-b54c-ef11b2e20107.png)

1. it seems to not recognize the show. Logs show this and I assume the api key is not used
`{"reqId":"lAD3GLk9HYsw6Ucj4bi3","level":3,"time":"2022-11-24T08:08:02+00:00","remoteAddr":"2003::4b48","user":"x","app":"PHP","method":"POST","url":"/index.php/apps/tvshownamer/scan","message":"file_get_contents(https://api.themoviedb.org/3/tv//season/3?api_key=): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized\r\n at /yaya/apps/tvshownamer/lib/Utils/TMDB.php#96","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 `
2. "Unable to find" is a link but leads nowhere
3. what is the meaning of "Nicht diese?" and "Nächste" ? Maybe the meaning becomes clearer when the show is recognized successfully?
4. If I check the box at "Dateiname", the label switches to english "File Name" (well, I do not really care ;)

**Comment by j4ym0** [comment]
Hey,

Yes I did make a error with a last minute change in the coding. This is now fixed in v0.4.1

Q1. A coding issue fixed.
Q2. This is usually a link to the show on TVDB - I will fix in later releases
Q3. This should make more sense when the show is available. In English should be “Not this one” and “Next” – I should review removing this.
Q4. This is to do with the Nextcloud translation witch has only been recently added to the app

You should remove the year from your folder name or add a # before the year e.g. “4 Blocks” or “4 Blocks #2017”. This is because it is difficult to filter out. The # will prompt the search to ignore after #

**Comment by wuppiwuppi** [comment]
kodi and jellyfin scrape the name very well like this. the year number is very important for a more precise matching. 
adding a # is not an option

**Comment by j4ym0** [comment]
Searching of a show title is relying on the tvdb search function.

I'm may be able in the future to try and present more turns to the search function if a title is not found by thetvdb.com. at the moment this is a dirty solution to a complex issue

**Comment by j4ym0** [comment]
Solution in v0.4.2
